vue-doc-cn:
  container_name: vue-doc-cn
  image: fellah/gitbook:latest
  ports:
    - "4000:4000"
  volumes:
    - ./:/srv/gitbook
    - ./:/srv/html
  command: gitbook init & gitbook build & gitbook serve
