version: '2'

services:
  vue-doc-cn:
    container_name: vue-doc-cn
    image: billryan/gitbook:latest
    ports:
      - "4000:4000"
    volumes:
      - ./:/gitbook
      - /usr/share/fonts:/usr/share/fonts
    entrypoint: ["/bin/bash", "-c"]
    command: /bin/bash
    stdin_open: true
    tty: true